In [5]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
root = Path("./results")

In [12]:
svd_results = pd.read_csv(root / "svd_results.csv")
svd_results = svd_results.sort_values("rank_test_rmse")
svd_results[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]

,mean_test_rmse,std_test_rmse,mean_test_mae,std_test_mae,rank_test_rmse,rank_test_mae,params
4,0.890102,0.005111,0.680302,0.004469,1,9,"{'n_factors': 1, 'n_epochs': 80, 'lr_all': 0.0..."
5,0.890169,0.005227,0.681140,0.004566,2,28,"{'n_factors': 1, 'n_epochs': 80, 'lr_all': 0.0..."
3,0.890187,0.005083,0.679452,0.004359,3,1,"{'n_factors': 1, 'n_epochs': 80, 'lr_all': 0.0..."
14,0.890276,0.005220,0.681091,0.004481,4,25,"{'n_factors': 1, 'n_epochs': 90, 'lr_all': 0.0..."
41,0.890316,0.005186,0.681115,0.004475,5,26,"{'n_factors': 2, 'n_epochs': 90, 'lr_all': 0.0..."
...,...,...,...,...,...,...,...
51,0.899074,0.004811,0.685476,0.003965,158,122,"{'n_factors': 2, 'n_epochs': 100, 'lr_all': 0...."
78,0.900305,0.004575,0.686039,0.003811,159,130,"{'n_factors': 3, 'n_epochs': 100, 'lr_all': 0...."
105,0.900797,0.005721,0.687122,0.004410,160,145,"{'n_factors': 5, 'n_epochs': 100, 'lr_all': 0...."
132,0.900987,0.005318,0.687254,0.004500,161,146,"{'n_factors': 7, 'n_epochs': 100, 'lr_all': 0...."
159,0.901092,0.005373,0.687915,0.004437,162,154,"{'n_factors': 10, 'n_epochs': 100, 'lr_all': 0..."

In [15]:
svd_pp_results = pd.read_csv(root / "svd++_results.csv")
svd_pp_results = svd_pp_results.sort_values("rank_test_rmse")
svd_pp_results[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]

,mean_test_rmse,std_test_rmse,mean_test_mae,std_test_mae,rank_test_rmse,rank_test_mae,params
4,0.891002,0.004127,0.680744,0.002812,1,2,"{'n_factors': 1, 'n_epochs': 80, 'lr_all': 0.0..."
14,0.891035,0.004282,0.681445,0.003130,2,6,"{'n_factors': 1, 'n_epochs': 90, 'lr_all': 0.0..."
5,0.891224,0.004170,0.681562,0.002986,3,7,"{'n_factors': 1, 'n_epochs': 80, 'lr_all': 0.0..."
3,0.891494,0.004311,0.680049,0.003039,4,1,"{'n_factors': 1, 'n_epochs': 80, 'lr_all': 0.0..."
13,0.891559,0.003712,0.681031,0.002642,5,3,"{'n_factors': 1, 'n_epochs': 90, 'lr_all': 0.0..."
...,...,...,...,...,...,...,...
160,0.915346,0.004563,0.698452,0.003827,158,158,"{'n_factors': 10, 'n_epochs': 100, 'lr_all': 0..."
150,0.916216,0.004062,0.698551,0.003452,159,159,"{'n_factors': 10, 'n_epochs': 90, 'lr_all': 0...."
105,0.916869,0.003727,0.698711,0.002794,160,160,"{'n_factors': 5, 'n_epochs': 100, 'lr_all': 0...."
132,0.917567,0.004578,0.700026,0.003422,161,161,"{'n_factors': 7, 'n_epochs': 100, 'lr_all': 0...."
159,0.919550,0.003760,0.701842,0.003358,162,162,"{'n_factors': 10, 'n_epochs': 100, 'lr_all': 0..."

In [13]:
nmf_results = pd.read_csv(root / "nmf_results.csv")
nmf_results = nmf_results.sort_values("rank_test_rmse")
nmf_results[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]

,mean_test_rmse,std_test_rmse,mean_test_mae,std_test_mae,rank_test_rmse,rank_test_mae,params
4,0.978206,0.004147,0.746760,0.003702,1,1,"{'n_factors': 1, 'n_epochs': 12, 'biased': True}"
2,0.978254,0.003747,0.749443,0.003384,2,2,"{'n_factors': 1, 'n_epochs': 10, 'biased': True}"
0,0.980802,0.003667,0.757589,0.002713,3,6,"{'n_factors': 1, 'n_epochs': 7, 'biased': True}"
8,0.988009,0.004476,0.755287,0.003117,4,4,"{'n_factors': 2, 'n_epochs': 10, 'biased': True}"
10,0.988827,0.003448,0.753341,0.002902,5,3,"{'n_factors': 2, 'n_epochs': 12, 'biased': True}"
6,0.989366,0.004416,0.761776,0.003148,6,12,"{'n_factors': 2, 'n_epochs': 7, 'biased': True}"
14,0.993166,0.003911,0.757973,0.003447,7,7,"{'n_factors': 3, 'n_epochs': 10, 'biased': True}"
12,0.993739,0.003698,0.763605,0.003042,8,13,"{'n_factors': 3, 'n_epochs': 7, 'biased': True}"
16,0.994210,0.004489,0.756481,0.003729,9,5,"{'n_factors': 3, 'n_epochs': 12, 'biased': True}"
18,0.996970,0.004574,0.765247,0.003375,10,14,"{'n_factors': 4, 'n_epochs': 7, 'biased': True}"
20,0.997092,0.004901,0.760142,0.004130,11,10,"{'n_factors': 4, 'n_epochs': 10, 'biased': True}"
22,0.997629,0.003518,0.758093,0.003141,12,8,"{'n_factors': 4, 'n_epochs': 12, 'biased': True}"
26,0.999433,0.003957,0.761014,0.002909,13,11,"{'n_factors': 5, 'n_epochs': 10, 'biased': True}"
24,0.999490,0.004159,0.765964,0.003220,14,15,"{'n_factors': 5, 'n_epochs': 7, 'biased': True}"
28,0.999890,0.003547,0.759353,0.003070,15,9,"{'n_factors': 5, 'n_epochs': 12, 'biased': True}"
29,1.136523,0.006044,0.844865,0.005111,16,16,"{'n_factors': 5, 'n_epochs': 12, 'biased': False}"
27,1.146705,0.005313,0.852365,0.004719,17,17,"{'n_factors': 5, 'n_epochs': 10, 'biased': False}"
25,1.170644,0.004974,0.919379,0.003867,18,20,"{'n_factors': 5, 'n_epochs': 7, 'biased': False}"
23,1.180094,0.006173,0.880719,0.005858,19,18,"{'n_factors': 4, 'n_epochs': 12, 'biased': False}"
21,1.197454,0.008384,0.897235,0.006673,20,19,"{'n_factors': 4, 'n_epochs': 10, 'biased': False}"
17,1.230448,0.004451,0.929635,0.004565,21,21,"{'n_factors': 3, 'n_epochs': 12, 'biased': False}"
15,1.264080,0.002997,0.961925,0.002748,22,22,"{'n_factors': 3, 'n_epochs': 10, 'biased': False}"
11,1.302860,0.004527,1.000173,0.003190,23,23,"{'n_factors': 2, 'n_epochs': 12, 'biased': False}"
19,1.316464,0.010374,1.069803,0.010702,24,25,"{'n_factors': 4, 'n_epochs': 7, 'biased': False}"
9,1.340625,0.007433,1.037436,0.006281,25,24,"{'n_factors': 2, 'n_epochs': 10, 'biased': False}"
5,1.390158,0.006333,1.088421,0.005040,26,26,"{'n_factors': 1, 'n_epochs': 12, 'biased': False}"
3,1.427812,0.006397,1.123420,0.005184,27,27,"{'n_factors': 1, 'n_epochs': 10, 'biased': False}"
13,1.531557,0.015040,1.290000,0.016448,28,28,"{'n_factors': 3, 'n_epochs': 7, 'biased': False}"
7,1.862161,0.015062,1.633107,0.015160,29,29,"{'n_factors': 2, 'n_epochs': 7, 'biased': False}"
1,2.335057,0.012099,2.139271,0.014195,30,30,"{'n_factors': 1, 'n_epochs': 7, 'biased': False}"

In [16]:
knn_basic_results = pd.read_csv(root / "knn_basic_results.csv")
knn_basic_results = knn_basic_results.sort_values("rank_test_rmse")
knn_basic_results[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]

,mean_test_rmse,std_test_rmse,mean_test_mae,std_test_mae,rank_test_rmse,rank_test_mae,params
71,1.076547,0.003552,0.806736,0.002147,1,4,"{'k': 60, 'sim_options': {'name': 'cosine', 'm..."
41,1.076623,0.003583,0.806835,0.002126,2,5,"{'k': 40, 'sim_options': {'name': 'cosine', 'm..."
11,1.076922,0.003580,0.807197,0.002126,3,6,"{'k': 20, 'sim_options': {'name': 'cosine', 'm..."
31,1.077542,0.004041,0.806322,0.002624,4,1,"{'k': 40, 'sim_options': {'name': 'msd', 'min_..."
61,1.077559,0.004037,0.806364,0.002618,5,3,"{'k': 60, 'sim_options': {'name': 'msd', 'min_..."
...,...,...,...,...,...,...,...
42,1.152801,0.003847,0.914890,0.003809,86,79,"{'k': 40, 'sim_options': {'name': 'cosine', 'm..."
72,1.152801,0.003848,0.914890,0.003814,87,80,"{'k': 60, 'sim_options': {'name': 'cosine', 'm..."
70,1.153014,0.005109,0.904837,0.004768,88,49,"{'k': 60, 'sim_options': {'name': 'cosine', 'm..."
40,1.153016,0.005110,0.904842,0.004766,89,50,"{'k': 40, 'sim_options': {'name': 'cosine', 'm..."
10,1.153106,0.005171,0.904937,0.004821,90,51,"{'k': 20, 'sim_options': {'name': 'cosine', 'm..."

In [17]:
knn_with_means_results = pd.read_csv(root / "knn_with_means_results.csv")
knn_with_means_results = knn_with_means_results.sort_values("rank_test_rmse")
knn_with_means_results[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]

,mean_test_rmse,std_test_rmse,mean_test_mae,std_test_mae,rank_test_rmse,rank_test_mae,params
88,1.020588,0.002362,0.759528,0.001455,1,1,"{'k': 60, 'sim_options': {'name': 'pearson', '..."
58,1.020589,0.002361,0.759528,0.001455,2,2,"{'k': 40, 'sim_options': {'name': 'pearson', '..."
28,1.020590,0.002359,0.759529,0.001454,3,3,"{'k': 20, 'sim_options': {'name': 'pearson', '..."
86,1.023730,0.003058,0.761998,0.001842,4,4,"{'k': 60, 'sim_options': {'name': 'pearson', '..."
56,1.023730,0.003058,0.761998,0.001842,5,5,"{'k': 40, 'sim_options': {'name': 'pearson', '..."
...,...,...,...,...,...,...,...
79,1.081835,0.001472,0.836623,0.001114,86,86,"{'k': 60, 'sim_options': {'name': 'cosine', 'm..."
49,1.081835,0.001472,0.836623,0.001114,87,87,"{'k': 40, 'sim_options': {'name': 'cosine', 'm..."
9,1.081881,0.001438,0.836633,0.001055,88,88,"{'k': 20, 'sim_options': {'name': 'msd', 'min_..."
69,1.081882,0.001438,0.836633,0.001055,89,89,"{'k': 60, 'sim_options': {'name': 'msd', 'min_..."
39,1.081882,0.001438,0.836633,0.001055,90,90,"{'k': 40, 'sim_options': {'name': 'msd', 'min_..."

In [ ]:
knn_with_z_score_results_df = pd.read_csv(root / "knn_with_z_score_results.csv")
knn_with_z_score_results_df = knn_with_z_score_results_df.sort_values("rank_test_rmse")
knn_with_z_score_results_df[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]

In [ ]:
knn_baseline_results_df = pd.read_csv(root / "knn_baseline_results.csv")
knn_baseline_results_df = knn_baseline_results_df.sort_values("rank_test_rmse")
knn_baseline_results_df[["mean_test_rmse", "std_test_rmse", "mean_test_mae", "std_test_mae", "rank_test_rmse", "rank_test_mae", "params"]]